### ISSUE TITLE
Difficulties to access UCUM ontology

### ISSUE THREAD

**Issue by GeorgFerdinandSchneider** [iot-ontologies/dogont#3]
Dear DogOnt team,

thanks for providing the DogOnt ontology on github.

I have problems to retrieve the UCUM ontology which is imported by DogOnt

[http://purl.oclc.org/NET/muo/ucum/](http://purl.oclc.org/NET/muo/ucum/)

Do you have any suggestions how to retrieve it?

Thanks!

Georg

**Comment by luigidr** [comment]
Hi Georg,

we are aware of the UCUM/MUO problem... as a temporary solution, the DogOnt ontology hosted in this repository uses a self-hosted version of both ucum-instances.owl and muo-vocab.owl files (with ad-hoc IRIs). See the `imported_ontologies` folder, for the OWL files of such ontologies.

We are planning to use the QUDT 2.0 ontologies (http://www.qudt.org/) for unit of measurements, once they will be released in their final and complete version.

**Comment by GeorgFerdinandSchneider** [comment]
Hi!

thanks for your answer. Its good to know you keep a local copy. It might make sense to add this to DogOnt maybe in a small comment or so.

Best

Georg
